@extends('layout')
@section('content')
<!-- Header -->
    <div class="col-md-10 col-md-offset-1" style="background-color: white">
        <div class="row" style="margin-top: 150px;margin-left: 10px;margin-right: 10px">
        <h2 class="text-muted" style="text-align: center">OFF GRID AND HYBRID SOLAR POWER SYSTEMS</h2>
        <h4 style="color: #fed136;">Off-Grid PV Systems</h4>
        <p class="text-muted">
            As  the  name  implies,  are  systems  that  are  not  connected  to  the  public  electricity  grid.  These
            systems  require  an  energy  storage  system  for  the  energy  generated  because  the  energy
            generated  is  not  usually  required  at  the  same  time  as  it  is  generated.Solar  energy  is  available
            during the day, but the lights in a stand-alone solar lighting system are used at night so the solar
            energy generated during the day must be stored for use at night. They are mostly used in areas
            where it is not  possible to install an electricity supply from the main utility grid, or where this is
            not  cost-effective  or  desirable.  They  are  therefore  preferable  for  developing  countries  where
            vast  areas  are  still  frequently  not  supplied  by  an  electrical  grid.  Off-grid  systems  are  usually
            employed  in  the  following  applications;  consumer  products    such  as  watches  and  scientific
            calculators, industrial applications such as telecommunications, Road constructions and roadside
            equipment powering    and traffic signs and remote habitations such as solar home systems and
            water pumping applications for both domestic and light irrigation requirements.
            A typical off-grid system comprises the following main components:<br>
            <b>• Solar PV Modules:</b> these convert sunlight directly to electricity.<br>
            <b>• Charge Controllers:</b> manage the charging and discharging of the batteries in order to maximize
            their lifetimes and minimize operational problems<br>
            <b>• Battery Or Battery Bank:</b> Stores the energy generated by the PV modules<br>
            <b>•  Inverter:</b>  converts  the  DC  current  generated  by  the  solar  PV  modules  to  AC  current  for  AC
            consumer  load.<br>
        </p>
        <div class="row">
            <div class="col-md-6">
                <img src="{{url('img/offgrid.png')}}">
            </div>
        </div>
        <div class="row">
            <hr>
        </div>
        <h4 style="color: #fed136;">Hybrid -Connected PV Systems</h4>
        <p class="text-muted">
            Hybrid -connected PV systems  are systems connected to an  independent grid usually the public
            electricity grid and feed power directly into the grid. These systems are usually employed in both
            decentralized  grid-connected  PV  applications  and  centralized  gridconnected  PV  applications.
            Decentralized  grid-connected  PV  applications  include  rooftop  PV  generators,  where  the  PV
            systems are mounted on rooftops of buildings and building integrated system in which the PV
            systems are incorporated into the building.  In the case of residential or building mounted grid
            connected PV systems, the electricity demand of the building is met by the PV system and the
            excess is fed into the grid; their capacities are usually in the lower range of kilowatts.
            A typical hybrid -connected PV system comprises the following components:<br>
            <b>• Solar PV Modules:</b> these convert sunlight directly to electricity.<br>
            <b>•Hybrid Inverter/power conditioner:</b>  converts the DC current generated by the solar PV modules
            to AC current for the utility grid<br>.
            <b>• Main disconnect/isolator Switch</b><br>
            <b>• Utility Grid</b><br>
            <b>Central Hybrid </b>-connected PV applications have capacities ranging from   kilowatts to  megawatts
            range.<br>
        </p>
        <div class="col-md-6">
            <img src="{{url('img/offgrid.png')}}">
        </div>
        </div>
    </div>
@endsection